### PR TITLE
Added New Voices and Screams

### PR DESCRIPTION
**Pull request by dangero2000**
I made a few voices for the voice list, and I added some screams as well. These screams are authentic, because at the time of recording, I was playing Screaming Strike and getting beaten up.

### CODE REVIEW

**Review by yncat — CHANGES_REQUESTED** [review]
Thank you for your first pull request.

Item voices are going to be merged all. Great additions!

About the screams, I'd like you to remove the following files:

- scream142
- scream143
- scream145
- scream146
- scream150
- scream151
- scream153
- scream154

Reason:
- These especially have large clippings and need to be excluded in my opinion.
- I want to keep the same kind of screams at most 4 or 5, because I don't want the game to become something like "punch and make a certain person scream over and over again" kind of thing. That's not an entertainment.

**Comment by dangero2000** [comment]
For sure, I can do that. Do I just make a new commit?

**Comment by ogomez92** [comment]
Hi, I'd say this is how pull requests work. You make a new commit with
your changes and the rest of us will get it.

**Comment by ogomez92** [comment]
Did you merge the pr before closing it' That was weird

**Pull request closed without merging**
