### PR TITLE
Deleted Requested Screams

### PR DESCRIPTION
**Pull request by dangero2000**
I deleted screams 142, 143, 145, 146, 150, 151, 153, and 154 due to clipping and to make sure people don't constantly hear my voice when punching people. My other screams have been renamed to keep up with proper numbering. Unfortunately, I'm struggling with the pull request system a little bit because this is a bit new for me, so I hope I'm requesting the right commit to be pulled.

### CODE REVIEW

**Comment by yncat** [comment]
I think you pressed "close and comment" instead of "comment" by mistake.
I'm going to review the files again and merge your commit later.

**Review by yncat — COMMENTED** [review]
Content is OK, but can you do the following?

run "git rebase -i HEAD~~"
(automatically opens an editor of your choice)
it should be like this:
pick commithash add voices and screams
pick anothercommithash delete screams
Change the second pick to fixup
Save the file and quit the editor.
The console should output "successfully rebased and updated refs"
After confirming the output, run "git push -f origin HEAD"
I want you to do this for optimizing the repository size. Without doing this, the deleted ogg files still remain in the repository since git records that they were present at the first commit and thus cannot be garbage collected by git.

**Comment by dangero2000** [comment]
After going back and forth with my computer for a while, I think I finally got it rebased. I was having so many issues with it that I'm not entirely certain I didn't mess things up, so you might want to double check to make sure I didn't. Bright side to this is if I ever have to rebase again, I shouldn't have the same issues I had this time. Victory, right?

**Comment by yncat** [comment]
@brogar2000 Your commits seem unchanged. Maybe you forgot to add -f switch when pushing?
Currently this pr's header shows "wants to merge 2 commits", but it should be 1.
If you're having difficulty with rebasing, it might be easier for you to do the following.

(1) copy files to add to somewhere else
(2) git checkout master
(3) git checkout -b newbranchname
(4) copy back your contents
(5) commit
(6) make a new pr and close this one

**Comment by dangero2000** [comment]
I think I've done it this time. I believe what I did wrong was I was using Nano as my editor, and I kept pressing Ctrl Z to exit,  when I should have pressed Ctrl X. Ctrl Z only suspends the editor, while Ctrl X quits the program like I was trying to do. As a side note, Git for Windows doesn't work well for me. I tried to enter my personal access token in the password field as you have to do now, because it doesn't accept password authentication anymore. When I entered my token though, it gave me an error saying I couldn't use my password and had to use a token, which is exactly what I did. In the end, I had to use my Debian server to push the changes. I think I've finally done it right though.

**Comment by yncat** [comment]
Yes, now it's perfect! Thank you very much for this.
Github recently dropped password support and switched to token-based authentication when using https. Since it sometimes causes problems like you experienced, I recommend using ssh with your own public / private key pair if you plan to contribute on github in the long term.

**Review by yncat — APPROVED** [review]
LGTM!

**Pull request merged**
