### PR TITLE
New scream sounds from voice actors

### PR DESCRIPTION
**Pull request by DraganRatkovich**
I've added 55 screaming sounds, some of which contain legendary voice actors like Steve Blum, who voiced Sub-Zero, Bo' Rai Cho, Reptile in Mortal Kombat X, plus more than two characters in Mortal Kombat 11 and many more game, Ashly Birch, legendary voice actor who also voiced Cassie Cage in Mortal Kombat X, Troy Edward Baker, voiced character Erron Black in Mortal Kombat x, etc. See if you can unlock these amazing actors and have fun with them in collections section.
@yncat Thanks for this awesome game.

### CODE REVIEW

**Comment by yncat** [comment]
Thank you for your pull request. I'm afraid we need to resolve the following two things in order to merge the changes into the official version, for quality control.

(1) Please show an evidence that these voices are legal.
(2) Please select 7 voices out of these.

**Comment by DraganRatkovich** [comment]
@yncat On demand, they're legal because they're lies on the net, but some of them, especially Steve's sounds, come from open source. Second, what do you mean by seven-voice choice?

**Comment by yncat** [comment]
Would you mind listing the websites?

As for the seven-file choice, I've decided to accept only 7 files from this pull request. Since there are a lot of similar screams and they're over 50 in total, accepting all of them results in nearly 25% of all screams from this pull request, which I want to avoid.

**Comment by DraganRatkovich** [comment]
@yncat You can of course check it out [here](https://www.sounds-resource.com/pc_computer/mortalkombatx/). As for the voices, you can exclude any voice you want, or whatever is easy for you, maybe I'll just edit the files and add only 5 or 6. If the website provided is not legal enough for you, you can simply merge my second commit, in which I edited the existing sounds in the game. I don't want to give you any legal trouble.

**Comment by yncat** [comment]
The website clearly says the voices are from Mortal Kombat, and it's obviously not legal.

**Pull request closed without merging**
